### PR TITLE
Fix #97

### LINKED ISSUE #97: toml config ignored
**Describe the bug**
`macchina.toml` settings are being ignored

**To Reproduce**
```
export XDG_CONFIG_HOME="$HOME/.config"
cd $XDG_CONFIG_HOME && mkdir macchina && cd macchina
wget macchina.toml https://raw.githubusercontent.com/Macchina-CLI/macchina/main/macchina.toml
```
I have restarted the terminal, re-sourced my shell configurations and so forth, but no changes occur. Must one specify explicitly that `macchina` must be reading the config via a flag or so?

**Expected behavior**
The configuration `.toml` changes the appearence of `macchina`.

**System Information**

Screenshot 2021-05-19 at 01 19 00

### PR DESCRIPTION
**Pull request by 123marvin123**

### CODE REVIEW

**Comment by 123marvin123** [comment]
Can you please check if everything still works properly under Linux? I did some refactoring and rewriting.

**Comment by grtcdr** [comment]
@123marvin123 I need your input to be able to progress on 6.0.2

**Comment by 123marvin123** [comment]
> @123marvin123 I need your input to be able to progress on 6.0.2

What exactly do you mean? I don’t see any notification.

**Comment by grtcdr** [comment]
I left a review up top :)

**Comment by 123marvin123** [comment]
Are you sure? I don't see a review and it still says "waiting for review" for your username.

**Comment by grtcdr** [comment]
Something is seriously wrong with GitHub, I'll resubmit the review.

**Comment by 123marvin123** [comment]
> Something is seriously wrong with GitHub, I'll resubmit the review.
> 
> EDIT: Crap, I actually left comments and not a review, can you see them?

Nope, I don't see any comments or reviews.

**Comment by 123marvin123** [comment]
I'll look at the issues you pointed out when I have some more time on my hands.

**Comment by grtcdr** [comment]
Just a small update on #97, it was resolved. Refactoring is welcome though.

**Pull request closed without merging**
