### PR TITLE
[WIP] Support Android (Termux)

### PR DESCRIPTION
**Pull request by laurentlbm**
This is a work in progress to support Android (initially probably just for Termux, not sure if anyone would want support of other terminal emulators). 

I'm looking for help, advice or comments. Also, I'm new to Rust, so feel free to bash the way I did things.

Some initial notes:
1. `/proc/cpuinfo` doesn't return the model name on the two devices I tested (Samsung A50 and Nexus 9 Tablet). I did a bunch of googling, and from what I gather, it's not easy to find out the model name on Android. There's a C library ([CPU INFOrmation](https://github.com/pytorch/cpuinfo)) that apparently can do it, but it has to check multiple Android properties and then do some logic to find a matching processor. We would have to have it as a dependency and update it when there's a new release. Also, I don't know how to call C from Rust yet. An alternative is to simply display the number of cores and the max frequency; that's what neofetch does.
2. I haven't figured out how to get into about the battery. The Linux way doesn't work. The data seems to only be available in the Android SDK in Java. Otherwise, Termux has a plugin app called Termux:API that adds a command to get battery stats, but it seems slow and it would require the user to have it installed.
3. To get the shell, I use the `$SHELL` environment variable, because I don't think Android allows you to change your shell, so the passwd file doesn't contain the shell info. Termux puts you in a modified environment though and you can change your shell there.

### CODE REVIEW

**Comment by grtcdr** [comment]
> This is a work in progress to support Android (initially probably just for Termux, not sure if anyone would want support of other terminal emulators).

Although I don't see an Android audience for Macchina, I'm not in any way against the idea of adding support for Android.
There's a lot of stuff missing right now, like ASCII art, and a lot of room for optimization, especially in the Linux implementation.
I can't promise that I'll look into this, but I'll keep an eye on your PR! :+1: 

> I'm looking for help, advice or comments. Also, I'm new to Rust, so feel free to bash the way I did things.
I'm new too, no one's bashing anyone on my watch haha :laughing:

**Comment by laurentlbm** [comment]
I'm mostly doing it for myself as a way to learn a little bit about Rust. I'll just try to get most of it working and see what happens.

For your information, [Termux](https://termux.com/) is a very popular terminal emulator for Android. It has 10M+ downloads on Google Play. It installs a base system for the user and has its own package manager. You can install ssh, rust, node, python, etc. It even has support for XFCE and you can use proot to install an actual Linux distribution (I personally haven't tried).

**Comment by grtcdr** [comment]
> I'm mostly doing it for myself as a way to learn a little bit about Rust. I'll just try to get most of it working and see what happens.

Awesome, have fun! :smile: 


> For your information, [Termux](https://termux.com/) is a very popular terminal emulator for Android. It has 10M+ downloads on Google Play. It installs a base system for the user and has its own package manager. You can install ssh, rust, node, python, etc. It even has support for XFCE and you can use proot to install an actual Linux distribution (I personally haven't tried).

I've never personally needed a terminal emulator for my Android :robot: device, but it seems like a lot people do!

**Comment by grtcdr** [comment]
Hey @laurentlbm, any progress?

**Comment by laurentlbm** [comment]
I've been sick, couldn't look into it ☹️

**Comment by grtcdr** [comment]
That's all right, get well soon!

I wanted to tell you that I have just started using Termux, and supporting Android seems like a good step forward, I'll be looking into it more in the future.

_libmacchina_ currently doesn't compile on Android as it conditionally compiles the readouts for each supported platform, and android isn't one of them, so going forward, we'll need to address this issue in 3 steps:
- Move this issue to _libmacchina_
- Create a new directory named `android` under `libmacchina/src` just like any other platform
- Implement readouts in the same manner as other platforms
  - If you encounter any issues implementing a certain readout, like battery for example, you could make the readout return `Err(ReadoutError::MetricNotAvailable)`, this will then show up in the output of `--doctor` notifying the user that the element could not be fetched.

**Pull request closed without merging**
