### PR TITLE
Add android ascii art

### PR DESCRIPTION
**Pull request by uttarayan21**
Added android ascii art both small and large

### CODE REVIEW

**Comment by grtcdr** [comment]
How do they look in the terminal?

**Comment by uttarayan21** [comment]
The normal ascii art.
ascii

I don't really know how to display the small one in terminal currently.
But yeah I agree , I'll try to make the small one simpler.

**Comment by grtcdr** [comment]
Small ASCII art is only displayed when 6 or fewer readouts are shown.

So If you do macchina -X memory, small ASCII will show up because only 1 readout is shown.

Here's what I can come up with:
```
   '      '
    '    '
  .oooooooo.
 .oo  oo  oo. 
 ooo  oo  ooo
 oooooooooooo
```

**Comment by grtcdr** [comment]
> Small ASCII art is only displayed when 6 or fewer readouts are shown.
> 
> So If you do macchina -X memory, small ASCII will show up because only 1 readout is shown.
> 
> Here's what I can come up with:
> 
> ```
>    '      '
>     '    '
>   .oooooooo.
>  .oo  oo  oo. 
>  ooo  oo  ooo
>  oooooooooooo
> ```

The eyes are a little bit large, so you can also try this if the one above is a little weird:
```
 :       :
  \     /
 .oooooooo.
.oooooooooo. 
ooo  oo  ooo
oooooooooooo
```

**Comment by uttarayan21** [comment]
Haha this is definitely a lot of fun.
ascii
This is what I ended up with.

**Comment by grtcdr** [comment]
> ascii

Can you try it without the body parts? Exceeding 6 or 7 lines looks off when only a few readouts are being displayed.

**Comment by uttarayan21** [comment]
Oh so you mean only the head.
Yeah that would also work.

**Comment by grtcdr** [comment]
> Oh so you mean only the head.
> Yeah that would also work.

Looks a lot neater in my opinion

**Comment by uttarayan21** [comment]
This definitely looks much better.
ascii

**Comment by grtcdr** [comment]
> This definitely looks much better.
Do you like the underscores? I made them to make the gap between the body and the head seem shorter, but I don't know if it looks that good...

**Comment by uttarayan21** [comment]
Yeah I think it looks pretty good.

But let me compile one without them for comparison.

**Comment by uttarayan21** [comment]
Here is a screenshot without hyphens.
ascii

IMO without the hyphens it looks kind of empty in the middle.

**Comment by grtcdr** [comment]
> IMO without the hyphens it looks kind of empty in the middle.
Yeah you're right.

**Review by grtcdr — CHANGES_REQUESTED** [review]
Last thing, replace the colons with dots in line 102
 
Span::styled("  :        :   ", *GREEN),

**Pull request merged**
