### PR TITLE
`v5.0`: breaking changes

### PR DESCRIPTION
**Pull request by grtcdr**
Previously in #176 

## What's new?
- Deprecation of command-line flags which have been moved to our theming system.
- Deprecation of built-in themes.

### CODE REVIEW

**Comment by 0323pin** [comment]
> I don't see PREFIX, but I did see someone comment that their LOCALBASE is their PREFIX (and it's set to the default value), is that what we're looking for?

In case LOCALBASE isn't set we'll default to /usr/pkg.

Yes, correct.
How many config files are you guys planning for?
Two? A theme file and a config file like in v4?

Where will `macchina` expect to find those? Both default and user configured?

Sorry for so many questions. Just trying to figure out what to expect.

**Comment by grtcdr** [comment]
> Sorry for so many questions. Just trying to figure out what to expect.

Don't apologize :)

> How many config files are you guys planning for?
>
>  Two? A theme file and a config file like in v4?

For now, macchina only requires a configuration file, as themes are optional, but you can package one of our themes in `${PREFIX}/macchina/themes` if you'd like.

> Where will macchina expect to find those? Both default and user configured?

As of right now, macchina looks for:
- its configuration in `XDG_CONFIG_HOME/macchina`.
- its themes in `XDG_CONFIG_HOME/macchina/themes` and `${PREFIX}/macchina/themes` on NetBSD.

**Comment by grtcdr** [comment]
I'll need a little bit of time to test if our LOCALBASE searching mechanism works as it should.

**Comment by grtcdr** [comment]
I emulated the searching mechanism on my Linux machine and it seems like everything is working.

`cat /etc/mk.conf`:
```
# PREFIX
LOCALBASE=/usr/pkg
```

`tree /usr/pkg`:
```
/usr/pkg/
└── macchina
    └── themes
        └── Titanium.toml
```

`macchina --list-themes`:
```
- Carbon
- Titanium
```

And you can of course set the theme.

**Comment by 0323pin** [comment]
> I emulated the searching mechanism on my Linux machine

Did you set-up pkgsrc on Arch?

> you can package one of our themes in ${PREFIX}/macchina/themes if you'd like.

I will do that but it will go into `${PREFIX}/share/examples/macchina` and then using a similar work around as in, _e.g._ `lxqt-policykit` copy it over to `${PREFIX}/etc`

**Comment by grtcdr** [comment]
> Did you set-up pkgsrc on Arch?

Nope, I just created a mock directory that has the same location as pkgsrc and used the same mk.conf as you guys do, just to test if our parser and searching works as it should.
 
> I will do that but it will go into `${PREFIX}/share/examples/macchina` and then using a similar work around as in, _e.g._ `lxqt-policykit` copy it over to `${PREFIX}/etc`, http://cvsweb.netbsd.org/bsdweb.cgi/pkgsrc/security/lxqt-policykit/Makefile?rev=1.11&content-type=text/x-cvsweb-markup

No worries, I'll update the path.

**Comment by 0323pin** [comment]
> No worries, I'll update the path.

No, don't!
Let's see if I manage to explain this...

Package should not install config files directly into `${PREFIX}/etc` but, they should expect to find them there.
We (NetBSD) will redirect these upstream config files to `{PREFIX}/share/examples` and tell in the package Makefile that these should be copied into `${PREFIX}/etc`.

Why do we do this "unnecessary" work? Because, users should, if they want, be able to store config files in the system wide directory, _i.e._ `${PREFIX}/etc` and, when the package gets updated it should not be able to replace these user configurations ;)

Hope I was clear?!

**Comment by grtcdr** [comment]
> Hope I was clear?!

Understood :)

We have something similar on Linux too, except you can't mess with the PREFIX AFAIK.

**Comment by 0323pin** [comment]
@grtcdr Cool, I will be building it today. Thanks for the new release.

A minor thing, like the first thing I saw on my mobile, in `macchina/themes/Helium.toml`, line 16, box title **Carbon**?

Sorry about that mate.

**Comment by grtcdr** [comment]
You're right, I totally missed that, I'll fix it.

**Pull request merged**
