### PR TITLE
Add command line argument for custom ascii art from file

### PR DESCRIPTION
**Pull request by CuriouslyCurious**
Fantastic tool, but I felt limited by just having the default ascii art or no art at all so I added a simple command line option to take a file path for a file to be displayed as ascii art instead of the default one.

Currently this PR is a draft as I'm just polling interest if this is a desired feature. If it is, before a merge I'd also like to be able to parse in the ANSI colour information from the given file but haven't gotten to that yet, currently it just prints everything blue as a placeholder.

For a bunch of distro ascii art to test with check neofetch's repo: [https://github.com/dylanaraps/neofetch/blob/master/neofetch#L5426](https://github.com/dylanaraps/neofetch/blob/master/neofetch#L5426)

image

### CODE REVIEW

**Comment by CuriouslyCurious** [comment]
> This is a desirable feature, I'd love to see land in the project so people can use Macchina more freely.
Great!

I'll keep poking around with this in the coming days to see if I can get a nice way to parse the ansi codes to a `tui::style::Color.` :P

**Comment by grtcdr** [comment]
> > This is a desirable feature, I'd love to see land in the project so people can use Macchina more freely.
> 
> Great!
> 
> I'll keep poking around with this in the coming days to see if I can get a nice way to parse the ansi codes to a `tui::style::Color.` :P

Awesome, can't wait to give it a go :smile: 

I'm always around if you need any help or have any questions.

**Comment by CuriouslyCurious** [comment]
> Here's an idea: instead of panicking when the given file is empty, ASCII should be completely disabled.
> 
> I detest panicking and I'm sure it scares newcomers and people who don't know much about programming or debugging.

Good philosophy to have. 

Will upload a commit with those changes in a moment.

**Comment by CuriouslyCurious** [comment]
Got a bit confused for a while why I couldn't just check `is_empty()`. Turns out I had to check for the underlying text's width.  :sweat_smile:

**Comment by grtcdr** [comment]
You got it haha

I was taking a look around crates.io to see what I can find under "ansi", I couldn't find a parser that can help us achieve what we want easily.

**Comment by grtcdr** [comment]
You could add a new flag that lets you change the ASCII color, with a requirement that custom_ascii flag is present.

This can override the ANSI codes the file might contain when we add support for it in the future.

**Comment by CuriouslyCurious** [comment]
> You could add a new flag that lets you change the ASCII color, with a requirement that custom_ascii flag is present.
>
> This can override the ANSI color codes the file might contain when we add support for it in the future.

Yeah, that'd be an easy way of doing it. I could try adding something like that.

I've looked at a few crates and experimented a little bit a.k.a struggled with properly reading stuff from bytes. From what I can gather however no crate as of now has support for parsing true color (24-bit color support in terminals). The most promising one for parsing just pure ANSI colours I've found is: [https://github.com/kurtlawrence/cansi](). It has no external dependencies and I don't think it would be too hard for me to add true color support to that crate in a PR. Famous last words, I know. :stuck_out_tongue:

**Comment by grtcdr** [comment]
> The most promising one for parsing just pure ANSI colours I've found is: https://github.com/kurtlawrence/cansi

I checked it out and yeah, seems like it would do the job!
It's very helpful for us that it doesn't have any external dependencies, as we're currently swimming in an ocean of them.

> Famous last words, I know. 

Exactly hahaha

**Review by grtcdr — CHANGES_REQUESTED** [review]
`custom-ascii-color` is descriptive but it's a bit too long, we should give a short value, "-A" for example.

**Comment by CuriouslyCurious** [comment]
> `custom-ascii-color` is descriptive but it's a bit too long, we should give a short value, "-A" for example.

Very true. I wonder if something like "-ca" (or even "-cac" if "-ca" gets used for `--custom-ascii`) might be better so it'll be less likely to collide with some other more important feature down the line wanting to use "-A"?

**Comment by grtcdr** [comment]
> Very true. I wonder if something like "-ca" (or even "-cac" if "-ca" gets used for `--custom-ascii`) might be better so it'll be less likely to collide with some other more important feature down the line wanting to use "-A"?

I'm pretty sure -ca expands to -c -a, so that wouldn't be possible. But there's really no need to worry about the future, there's still around 18 characters in the alphabet we still haven't used.

**Comment by CuriouslyCurious** [comment]
> > Very true. I wonder if something like "-ca" (or even "-cac" if "-ca" gets used for `--custom-ascii`) might be better so it'll be less likely to collide with some other more important feature down the line wanting to use "-A"?
> 
> I'm pretty sure -ca expands to -c -a, so that wouldn't be possible. But there's really no need to worry about the future, there's still around 18 characters in the alphabet we still haven't used.

Oh, so it seems. I'll use "-A" then.

**Comment by grtcdr** [comment]
Hey @CuriouslyCurious !

So how's it all coming?

**Comment by CuriouslyCurious** [comment]
> Hey @CuriouslyCurious !
> 
> So how's it all coming?

Hiya.

Been looking through cansi crate and noticed that it doesn't handle using a octal escape code (`\033`), and since Rust for some reason doesn't handle octal escape code (only hex) it becomes a bit harder to achieve proper support. `\033` becomes an invalid utf-8 character (interpreted as `\0` null terminator) and thus causes the whole thing to just panic. The crate uses string slices everywhere, and those would mostly need to be replaced with byte slices to fix this. It handles `\x1b` correctly however. I think this may be an oversight or a simplification on the maintainer's end.

Adding the custom truecolor stuff seems to be fairly simple however, so there's that. :P

All in all, they were indeed some famous last words. :sweat_smile:

I'll try to get some work in on the cansi PR today, but seeing as it would delay this PR we could just finalize the custom ascii art and add in colour support later down the line.

**Comment by CuriouslyCurious** [comment]
> Hey there!
> 
> We can implement our own color code variables, can we not?
> Sure, it might be unintuitive for the user, but we have a wiki for these kinds of things, where we elaborate on certain aspects that aren't mentioned in the README for the sake of simplicity.

Oh, yeah. You'd still have to parse the given file for these variables and convert them to `tui` colors. Certainly an option. Maybe having the syntax be similar to what neofetch does internally something like `${<color>}` or simply `{r,g,b}` and just intersperse those around in the ascii art file.
 
> I am fine with merging this for the moment, but I think it would be amazing to make our own stuff.

Sounds good. I'll keep bashing my head at `cansi` library rewrite when I have the time. I think I can get it to work.

Is there anything that needs polishing up before merging?

**Review by grtcdr — APPROVED** [review]
Looks good :smile:

**Pull request merged**
