### PR TITLE
Include commit hash in version info

### PR DESCRIPTION
**Pull request by uttarayan21**
Show the commit from which macchina was built.
macchina

### CODE REVIEW

**Comment by uttarayan21** [comment]
I'll also try to include the version of libmacchina used to build and maybe its commit hash too.
Might help us debug issues easily.
Also will need to remove the autocompletion generation for this to work.

**Comment by grtcdr** [comment]
This is a really good idea!

**Comment by grtcdr** [comment]
I was never really satisfied with the way autocompletion was integrated, so I don't mind it disappearing for a little while until we can rewrite it without it depending on a bunch of crates.

**Review by grtcdr — APPROVED** [review]
Looks good :rocket:

**Comment by uttarayan21** [comment]
> I was never really satisfied with the way autocompletion was integrated, so I don't mind it disappearing for a little while until we can rewrite it without it depending on a bunch of crates.

Great ! Then I just need to figure out how to add the commit hash of libmacchina to this as well

**Comment by grtcdr** [comment]
> Great ! Then I just need to figure out how to add the commit hash of libmacchina to this as well

Even better :+1:

**Review by grtcdr — APPROVED** [review]

**Comment by grtcdr** [comment]
After looking through vergen's docs, I couldn't seem to find a straightforward way to print out a different crate's SHA hash

**Comment by grtcdr** [comment]
What are your plans?

**Comment by uttarayan21** [comment]
Oh I have already done in the last two commits. You can check it out.

**Comment by grtcdr** [comment]
Oh I must have missed that! Are we ready to merge?

**Comment by uttarayan21** [comment]
I think we are mostly ready. Just need to do a bit more testing.

**Comment by uttarayan21** [comment]
Checks should work after libmacchina 0.8.0 is up. ( https://github.com/Macchina-CLI/libmacchina/pull/51 )

**Review by grtcdr — APPROVED** [review]

**Comment by uttarayan21** [comment]
Seems like something went wrong! Can't seem to find out right now. I will check tomorrow.

**Comment by grtcdr** [comment]
Yeah it's failing at libmacchina's config unwrap, which is weird because it builds fine on my machine.

**Comment by uttarayan21** [comment]
Yeah thats the same for me too. I'll check check vergen docs to find something.

**Comment by grtcdr** [comment]
Could it be the absence of _libmacchina_'s .git directory seeing as it's a crate?

**Comment by uttarayan21** [comment]
https://docs.rs/crate/libmacchina/0.7.9/source/


Seems like that is the case. I'll look for some way.

**Comment by uttarayan21** [comment]
Should be fixed now.
I have checked by removing the .git folder from my local repo.

**Review by grtcdr — APPROVED** [review]

**Pull request merged**
