### PR TITLE
Add support for rgb and indexed colors

### PR DESCRIPTION
**Pull request by uttarayan21**
Added support for rgb and indexed colors by using cusom de/serialization of the `tui::style::Color` struct.

Source here https://git.uttarayan.me/uttarayan/color-parser-tui. I will publish to crates.io after a bit more testing.

### CODE REVIEW

**Review by grtcdr — APPROVED** [review]
LGTM.

(Renaming theme::theme to theme::base is a very welcome change)

**Comment by grtcdr** [comment]
You should consider publishing the library, as lots of other people might find it useful like with your other _tui_ crate.

**Comment by grtcdr** [comment]
Your crate sorta makes `theme::color::MacchinaColor` obsolete, should we remove ours?

**Comment by uttarayan21** [comment]
Actually now that I took a look it seems that MacchinaColor was a wrapper enum to use Color with clap. Now that it's not required, we can probably remove it.

**Comment by grtcdr** [comment]
> Hmm I haven't really looked at `MacchinaColor` closely I just Renamed MacchinaColor to Color and fixed the compiler errors, and it just worked.

It implements Deserializer and Serializer, that's about it. And your crate implements that as well, so how should we proceed?

**Comment by uttarayan21** [comment]
There's a `make_random_color` function closure in main that needs to be manually rewritten I guess. Other than that I can remove it.

**Comment by grtcdr** [comment]
I've been playing around with `strum` and `strum_macros` which provide EnumString and EnumIter. The issue with using `arg_enum!` is it just doesn't allow enumerations that use constructors, which we need for `Rgb(u8, u8, u8)`. For `Enum::variants()` we can use `Enum::iter().collect()`.

**Comment by grtcdr** [comment]
Before I forget, this should probably be merged into `v6`.

**Comment by uttarayan21** [comment]
Removed `MacchinaColor`. Updated color-parser-tui with a module optional which add support for `Option<Color>`

**Review by grtcdr — APPROVED** [review]
Are we ready to merge to the `v6` branch?

I'd rather bundle up our new features into one major release this time.

**Comment by uttarayan21** [comment]
It's core logic is done. Ill just need to clean up the code a bit, add better docs, and add a few more tests.

I'll probably publish it on saturday after all is done.

**Comment by grtcdr** [comment]
Take your time, v6 is probably a long way from being ready.

**Comment by uttarayan21** [comment]
Is the name of the crate alright ?. I was thinking to name it similar to `ansi-to-tui`, and make it `hex-to-tui` or `color-to-tui`.

Any suggestions ?

**Comment by grtcdr** [comment]
If I were you, I'd name it the way I name most of my crates, in Esperanto. So "koloro" in this case.

**Comment by uttarayan21** [comment]
I mean if I made a standalone crate I might consider it. But this is just a helper crate of sorts, so I think it might be better to name it descriptive.

**Comment by grtcdr** [comment]
Then `color-to-tui` it is. I like that.

**Comment by grtcdr** [comment]
Ready to merge into `v6`?

**Comment by uttarayan21** [comment]
Yes. Let me know if something needs to be changed.

**Comment by grtcdr** [comment]
As far as I can see, everything looks great :)

**Comment by uttarayan21** [comment]
Rebased to v6 branch.

**Comment by uttarayan21** [comment]
I think we need to show the parsing errors to the users. I can't figure out what is wrong with `Hydrogen.toml`

**Comment by grtcdr** [comment]
We really do, in the meantime, can you show me the file?

**Comment by uttarayan21** [comment]
```toml
# for a complete reference, visit
# https://github.com/Macchina-CLI/macchina/wiki/Theme-Documentation

spacing = 2
padding = 0
hide_ascii = false
hide_bar_delimiters = true
prefer_small_ascii = false
separator = ">"
key_color = "#ff6135"
separator_color = "#0ac365"
palette = "Light"

[bar]
glyph = "ߋ"
symbol_open = '['
symbol_close = ']'
visible = true

[box]
title = "aurc"
visible = true

[box.inner_margin]
x = 1
y = 0

[custom_ascii]
# color = "Green"
path = "~/.config/macchina/ascii/archlinux.ascii"

[randomize]
key_color = false
separator_color = false

[keys]
host = "Host"
kernel = "Kernel"
battery = "Battery"
os = "OS"
de = "DE"
wm = "WM"
distro = "Distro"
terminal = "Terminal"
shell = "Shell"
packages = "Packages"
uptime = "Uptime"
memory = "Memory"
machine = "Machine"
local_ip = "Local IP"
backlight = "Brightness"
resolution = "Resolution"
cpu_load = "CPU Load"
cpu = "CPU"
```

Its this one.
Meanwhile I'll try make another pr to show the parsing error

**Comment by grtcdr** [comment]
The theme parses and shows up correctly when building the usual `macchina/main`, but it fails on this specific branch/fork, did we deprecate something and not notice?

**Comment by uttarayan21** [comment]
Oh I forgot to mention, I figured it out.
There were no `#[serde(default)]` in Block and Bar structs so It failed to derive with missing values.

**Comment by grtcdr** [comment]
Good catch :)

**Comment by uttarayan21** [comment]
I actually hadn't pushed the #[serde(default)]  changes. I'll merge them in #208

**Comment by grtcdr** [comment]
> I actually hadn't pushed the #[serde(default)] changes. I'll merge them in #208

Woops, alright :)

**Pull request merged**
