### PR TITLE
Add a resolution readout

### PR DESCRIPTION
**Pull request by grtcdr**
- Add a resolution readout for the newly implemented resolution function in **libmacchina**
- Bump libmacchina to _v0.4.8_

image

### CODE REVIEW

**Review by uttarayan21 — APPROVED** [review]
Works fine on my linux machine

**Comment by grtcdr** [comment]
Great! I'm surprised we have broken builds, what could be the reason it can't link with `cc`?

**Comment by grtcdr** [comment]
Any way we can tell `rustc` not to fail when it can't find the X11 library?

**Comment by grtcdr** [comment]
NetBSD's refusing to work...

**Comment by uttarayan21** [comment]
https://github.com/Macchina-CLI/libmacchina/blob/19ec1edd00cd9ba4801fba88c49ff27a6eb3a54b/src/netbsd/mod.rs#L163
You need to `mod x11_ffi` at the top before use.

**Comment by grtcdr** [comment]
> https://github.com/Macchina-CLI/libmacchina/blob/19ec1edd00cd9ba4801fba88c49ff27a6eb3a54b/src/netbsd/mod.rs#L163
> You need to `mod x11_ffi` at the top before use.

I completely missed that! Nice catch :)

**Comment by grtcdr** [comment]
@uttarayan21 Any idea how we can get resolution info on _Android_?

**Comment by uttarayan21** [comment]
Didn't really find anything related to the resolution in android.
I'll try find out more.

**Comment by grtcdr** [comment]
> Didn't really find anything related to the resolution in android.
> I'll try find out more.

Awesome! :+1:

**Pull request merged**
