### PR TITLE
Add instructions for Fedora installation

### PR DESCRIPTION
**Pull request by VarLad**

### CODE REVIEW

**Comment by grtcdr** [comment]
Hi! 

Thank you for taking the time to maintain a build for Fedora :smile: I have a question regarding the installing of rustup. 

The official website uses:

```
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
```

While your build script uses:

```
curl https://sh.rustup.rs -sSf | sh -s -- --profile minimal -y
```

Why are they different?

If it's possible, can we avoid `curl ... | sh`, it makes me uncomfortable... :/

**Comment by VarLad** [comment]
@grtcdr Its just there as a formality if in the future someone (or me) wants to fork and use the script for building for RHEL

I can remove that part altogether if you want, or change it to `curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh`, but it won't effect the build since its only for Fedora 35 and Fedora Rawhide (both x86_64)

**Comment by grtcdr** [comment]
Is there a proper package you can depend on instead of using the possible vulnerable way of curling and piping to sh like the Rust website says?

**Comment by VarLad** [comment]
The build uses the `rust` package available in the official Fedora repos and not the one by `curl`

The curl one will be used if someone enables the build for RHEL in the future

**Comment by grtcdr** [comment]
> The build uses the `rust` package available in the official Fedora repos and not the one by `curl` from the Rust site
> 
> The curl one will be used if someone enables the build for RHEL in the future

Oh, understood :)

I'll merge it in then!

Thank you :heart:

**Pull request merged**
