### PR TITLE
Add config option to set presets

### LINKED ISSUE #83: [Question] About the creation of a configuration file
By default `macchina` displays all system information in a default format. To change this, one must make use of the many options available (and there seem to be more and more of them). And this can sometimes result in a rather long command.

I'm not sure what the future plans of the project are, but it occurs to me that creating a configuration file from which to read the `macchina` defaults might be a good idea. Of course this is not the only way to solve the above problem; on Linux systems you could create an `alias` that runs `macchina` with the desired options.

I have also tried the different themes offered by the application. My question is, are there any plans to add custom themes? It could be an alternative to the configuration file.

Of course, whichever way you go, it's not something that will be done overnight. But whatever I can do to help, I'm willing.

### PR DESCRIPTION
**Pull request by uttarayan21**
Fixes #83 
example

example-config

### CODE REVIEW

**Comment by grtcdr** [comment]
We're missing `color` and `separator_color`

**Comment by uttarayan21** [comment]
Oh I just removed a few of stuff from the config just to show that the config can work without all the stuff already set.

**Comment by grtcdr** [comment]
Oh great!

This also made me realize that **Xinitrc** is setting itself in one of the environment variables that tell us which DE you're running, I'll add a new exception for Xinitrc ASAP.

**Comment by uttarayan21** [comment]
Oh don't worry about that. I have a bit of a quirky setup which makes `Xinitrc` show up as an item in lightdm's DM selection menu.
So that's why macchina thinks Xinitrc is my dm.

**Comment by grtcdr** [comment]
> Oh don't worry about that. I have a bit of a quirky setup which makes `Xinitrc` show up as an item in lightdm's DM selection menu.
> So that's why macchina thinks Xinitrc is my dm.

No worries, we still have to account for the quirkiness of some setups, if you look around libmacchina you'll notice certain operations and exceptions that seem weird at first, but they were added because I noticed weird output on some people's machines.

**Comment by grtcdr** [comment]
I think the next step for the config file is to allow for custom theming, the way we can go about is to initialize a placeholder theme in `theme.rs` whose fields will take the values of say:
```Rust

separator_glyph
bar_glyph
// The opening bar delimiter
bar_delimiter_open
// The closing bar delimiter
bar_delimiter_close
```

And if we're really ambitious we can allow for custom abbreviations, here's a little example:
```
window_manager_string = "WM"
desktop_environment_string = "DE"
...
```

The key naming choice is up for debate, I'm not sure `window_manager_string` is that great of a name.

**Comment by uttarayan21** [comment]
Ah okay so I'll have to look into dividing the config into theme sections.

Something like
```toml
[config]
palette = true
no_color = false
no_separator = false
no_bar_delimiter = false
no_title = true
no_ascii = true
no_box = true
bar = true
random_color = false
random_sep_color = false
short_uptime = false
short_shell = true
theme = 'Boron'
custom_ascii = '/home/fs0c131y/.config/ascii/archlinux.ascii'

[theme]
name = 'MyTheme'
window_manager_string = 'WM'
```

**Comment by grtcdr** [comment]
> Ah okay so I'll have to look into dividing the config into theme ~sections~ files.
> 
> Something like
> 
> ```toml
> [config]
> palette = true
> no_color = false
> no_separator = false
> no_bar_delimiter = false
> no_title = true
> no_ascii = true
> no_box = true
> bar = true
> random_color = false
> random_sep_color = false
> short_uptime = false
> short_shell = true
> theme = 'Boron'
> custom_ascii = '/home/fs0c131y/.config/ascii/archlinux.ascii'
> ```
> 
> and
> `Mytheme.toml`
> 
> ```toml
> [theme]
> name = 'MyTheme'
> window_manager_string = 'WM'
> ```
> 
> Edit: Hmmm it seems that the toml spec cannot have multiple keys with same name so we will have to split the themes into seperate files.

Separate files is definitely a better idea.

**Comment by uttarayan21** [comment]
Okay so I was looking into serializing themes from a file and I have a few design related questions.

- Should we keep the hydrogen, lithium and the other themes in the theme.rs or should we seperate them into Hydrogen.toml and similar files ?
IMO It should be able to perform just as a single binary so I'd keep at least a default theme in it.
- Should we keep the theme.rs as is and make a separate module for parsing themes ?

**Comment by uttarayan21** [comment]
Okay so I'm going to implement it as such

1. Check theme name from config.
2. If theme matches inbuilt themes then display that.
3. else try to parse a file in `dirs::data_dir()/macchina/themes/` folder.
4. If everything else fails, default to the hydrogen theme.

**Comment by uttarayan21** [comment]
Okay so I was implementing the custom themes and I think I have to restructure the themes module quite a bit to make both inbuilt and custom themes work at the same 

Also since the theme argument used to be an enum I'll need to change it to a string to work with custom values.

Also this will break auto generated autocomplete for --themes argument, (since we don't know all the variants anymore) but a custom one can be written.

**Comment by grtcdr** [comment]
> Also since the theme argument used to be an enum I'll need to change it to a string to work with custom values.

We can do this without removing the enum, when matching the `--theme` argument, if the argument isn't one of the default themes, then we can assume the argument is a path to a file.

> Okay so I was implementing the custom themes and I think I have to restructure the themes module quite a bit to make both inbuilt and custom themes work at the same

How so? I feel like the only change that needs to happen is a placeholder theme that is filled with the values found in a given `theme.toml`, but then again, I may be missing something.

> Also a question about `ReadoutKey.get_common_name()`, should it also be theme-able ?

Um, I think so? (key names are considered an `AbbreviationType` and should go through `get_common_name()`)

**Comment by uttarayan21** [comment]
> We can do this without removing the enum, when matching the --theme argument, if the argument isn't one of the default themes, then we can assume the argument is a path to a file.
```rust
    #[structopt(
    short = "t",
    long = "theme",
    default_value = "Hydrogen",
    possible_values = & theme::Themes::variants(),
    case_insensitive = true,
    help = "Specify the theme"
    )]
    pub theme: Option<theme::Themes>,
```

Theme argument directly take enum values only and AFAIK we can't make new enum variant's at runtime with custom theme names.
And matching against the enum variants is done automatically by structopt/clap so we can't add additional logic there.

> How so? I feel like the only change that needs to happen is a placeholder theme that is filled with the values found in a given theme.toml, but then again, I may be missing something.

This is mostly because most of the getter setter functions are redundant since all of them are basically the same.
So I was thinking about a maybe default implementation and overwrite it when necessary.
Also the new fucntion needs to be removed from the trait to a standard impl since `CustomTheme` cannot have a new function since we need a name for the theme to be provided.

> But I'm sure you can bypass this process if custom key names are provided in the config.

I'll look into it after I have completed the rest of the theming.

**Comment by grtcdr** [comment]
> Theme argument directly take enum values only and AFAIK we can't make new enum variant's at runtime with custom theme names.
> And matching against the enum variants is done automatically by structopt/clap so we can't add additional logic there.

That is true, I'm sort of getting rusty at writing Rust code since most of my time has been taken up by PHP, and so I keep forgetting these details.


> This is mostly because most of the getter setter functions are redundant since all of them are basically the same.

I did notice this a while back, you're absolutely right.

> So I was thinking about a maybe default implementation and overwrite it when necessary.

Sounds good :)

> Also the new fucntion needs to be removed from the trait to a standard impl since `CustomTheme` cannot have a new function since we need a name for the theme to be provided.

So a custom theme is *not* a `Path` but is extracted from the entries of the `macchina` directory within `dirs::data_dirs`?

**Comment by grtcdr** [comment]
I'm all for this!

It looks to me like the configuration system is tightly joined together and it's pretty dope!

**Comment by uttarayan21** [comment]
Huh It seems that rust doesn't have fields in traits so we still need to do the getter/setter madness until the rfc is merged.

**Comment by uttarayan21** [comment]
Sure,
Here you go.
https://github.com/nikomatsakis/fields-in-traits-rfc/blob/master/0000-fields-in-traits.md
https://github.com/rust-lang/rfcs/pull/1546
https://internals.rust-lang.org/t/fields-in-traits/6933

**Comment by grtcdr** [comment]
> Sure,
> Here you go.
> https://github.com/nikomatsakis/fields-in-traits-rfc/blob/master/0000-fields-in-traits.md
> [rust-lang/rfcs#1546](https://github.com/rust-lang/rfcs/pull/1546)
> https://internals.rust-lang.org/t/fields-in-traits/6933

Thank you so much!

**Comment by uttarayan21** [comment]
So I've done a basic implementation of the themes.
Had to restructure a lot of the stuff but custom themes are working now.

config
macchina

**Comment by grtcdr** [comment]
I'm loving the new changes so far :partying_face: thanks for all your hard work!

It's kind of late right now, I'll review and test the new changes and features tomorrow.

**Comment by uttarayan21** [comment]
You can test if you want but it will panic if anything is wrong since error handling is not in place yet.

**Comment by uttarayan21** [comment]
@grtcdr 
I'm changing the custom themes to json since writing it in toml is very awkward,
since it doesn't have a way to represent enum with tuples (for `Rgb(u8, u8, u8)` true colors).

In json writing theme is really simple since you can basically repesent enums/structs in a pretty simple way.

**Comment by grtcdr** [comment]
I feel the same way too, and a lot of people are already very familiar with JSON as opposed to TOML.

**Comment by uttarayan21** [comment]
Great , so the only thing left for me to implement is the abbreviation stuff and write some docs. I'll try to make the final commit tomorrow.

**Comment by grtcdr** [comment]
> Great , so the only thing left for me to implement is the abbreviation stuff and write some docs. I'll try to make the final commit tomorrow.

Oh so you implemented error handling? I've only reviewed parts of the code and waiting for a final version to spend some time testing and stuff.

**Comment by uttarayan21** [comment]
Yeah already implemented error handling yesterday :).
You can review it now if you want.

> I feel like a very nice addition is to create a config directory within the main directory, like contrib, which contains some pre-configured dotfiles, you might throw in your favorite config of macchina in there, and I can throw in mine too :)

Haha sure I'll include mine. 
Also I'll include some theme examples too.

**Comment by grtcdr** [comment]
> Yeah already implemented error handling yesterday :).

Great!

> You can review it now if you want.

Will do :)

> Haha sure I'll include mine.
> Also I'll include some theme examples too.

Yeah, that too is a good addition :smile:

**Comment by grtcdr** [comment]
There's one thing we might want to address before merging, that is the conflict between hide and show_only within the configuration file.

**Comment by uttarayan21** [comment]
Is `patch_args` the appropriate place to set a condition for their coexistance?

I mean it would work but I think it should be done in a separate function like `check_conflicts`.

**Comment by uttarayan21** [comment]
Or possibly directly inside of `from_config` and return an error if it has conflicts.

**Comment by grtcdr** [comment]
> Is `patch_args` the appropriate place to set a condition for their coexistance?
> 
> I mean it would work but I think it should be done in a separate function like `check_conflicts`.

Alrighty, I could take care of it if you'd like.

**Comment by uttarayan21** [comment]
> Alrighty, I could take care of it if you'd like.

Sure ! I also have some more changes locally I need to commit.

**Comment by grtcdr** [comment]
> > Alrighty, I could take care of it if you'd like.
> 
> Sure ! I also have some more changes locally I need to commit.

Great :)

**Review by grtcdr — APPROVED** [review]

**Comment by uttarayan21** [comment]
I'll include a custom theme
Give me a second

**Comment by grtcdr** [comment]
> I'll include a custom theme
> Give me a second

Sure!

**Comment by uttarayan21** [comment]
Screenshot from 2021-05-16 22-18-45

A screenshot of theme I included.

**Comment by uttarayan21** [comment]
A few notes.
- `theme` field should have the exact filename for custom themes without extensions. i.e. for `Carbon.json` -> `"Carbon"`
- Custom themes support truecolor (24-bit) and 256 (8-bit) colors in addition to the 4-bit color pallet.
- Both theme and config options are case-sensitive.

**Review by grtcdr — APPROVED** [review]

**Comment by grtcdr** [comment]
> A few notes.
> 
>     * `theme` field should have the exact filename for custom themes without extensions. i.e. for `Carbon.json` -> `"Carbon"`
> 
>     * Custom themes support truecolor (24-bit) and 256 (8-bit) colors in addition to the 4-bit color pallet.
> 
>     * Both theme and config options are case-sensitive.

Thanks for the clarification, I'll make sure to include this when I update the READMEs.

**Comment by grtcdr** [comment]
I managed to make the config conflict check work and also report which keys are conflicting, check it out and tell me if anything needs to be changed.

image

**Comment by uttarayan21** [comment]
Looks great but I think you forgot to push the commit :).

**Comment by grtcdr** [comment]
> Looks great but I think you forgot to push the commit :).

Yeah, just cleaning up a bit.

**Review by uttarayan21 — COMMENTED** [review]
Looks good !

**Comment by grtcdr** [comment]
> Looks good !

Terrific work by the way! :rocket:

**Comment by uttarayan21** [comment]
> > Looks good !
> 
> Terrific work by the way! 🚀

Haha, thanks ! :)

**Pull request merged**
