### PR TITLE
refactor: theme handling

### PR DESCRIPTION
**Pull request by grtcdr**

### CODE REVIEW

**Comment by grtcdr** [comment]
@uttarayan21 Looks like we're getting some errors on Android, ever since I bumped [if-addrs] to version 0.7.0).

Any clue why this might be happening? The crate's maintainer actually published this new version which should've [fixed whatever issues](https://github.com/messense/if-addrs/commit/d443bc133678f32be8e3623dcd632e786171d04c) occurring on Android. I'm going over the source to try and make sense of what's happening.

**Comment by uttarayan21** [comment]
Since the issue seems to be fixed I guess I don't need to look into it anymore.

Also currently this PR doesn't give an error when no theme is found / invalid theme name is used.

**Comment by grtcdr** [comment]
> Since the issue seems to be fixed I guess I don't need to look into it anymore.

Well no, the issue only appeared after the supposed fix for Android.

> Also currently this PR doesn't give an error when no theme is found / invalid theme name is used.

I haven't rebased this branch yet.

**Comment by uttarayan21** [comment]
I just skimmed the error messages. Seems like the issue is originating from [here](https://github.com/Macchina-CLI/macchina/runs/4652689528?check_suite_focus=true#step:6:69)

``` /cargo/registry/src/github.com-1ecc6299db9ec823/if-addrs-0.7.0/src/posix.rs:43: undefined reference to `getifaddrs'```

Currently I think it might be due to linking against mismatching android libraries ( target sdk version ).

**Comment by grtcdr** [comment]
Could you check it out?

**Comment by uttarayan21** [comment]
Sure. I'll take a look at it. If we can't fix it we can just rollback the version too right ?

**Comment by grtcdr** [comment]
Yep, of course.

**Pull request merged**
