### PR TITLE
Show parsing errors and switch error handling to anyhow crate.

### PR DESCRIPTION
**Pull request by uttarayan21**
Show errors while parsing the theme files.

Screenshot from 2021-11-07 20-10-20

### CODE REVIEW

**Comment by uttarayan21** [comment]
Need to merge after #193 is merged to v6

**Comment by grtcdr** [comment]
Very nice!!

Although the formatting could be better, maybe play around with it and print something cool, in the sense that, "you broke macchina", but the error output is _clean._

**Comment by grtcdr** [comment]
Should I review it?

**Comment by uttarayan21** [comment]
Not yet I need to make some major changes to make it pretty-print the errors, I think.

**Comment by grtcdr** [comment]
Ah, okay :)

I'm working on rewriting some stuff on the Linux side; mostly experimenting with some optimizations.

**Comment by uttarayan21** [comment]
I'll be busy with work this week I'll try to complete the changes on the weekend.

If you complete your changes you can push it ot v6 and I'll rebase this branch.

**Comment by grtcdr** [comment]
Hey, any progress?

**Comment by uttarayan21** [comment]
Sorry didn't really have time this weekend. I'll try to complete it after work today or tomorrow.

Nov 15, 2021 7:16:57 PM Aziz Ben Ali ***@***.***>:

**Comment by uttarayan21** [comment]
Yeah same for me been a busy week. Didn't really feel like working with
rust after working the whole week with it.

-- 
Uttarayan Mondal

**Comment by grtcdr** [comment]
Yeah, don't burn yourself out :)

**Comment by grtcdr** [comment]
Not sure if we can customize anyhow's error reports, there's a crate called [eyre](https://github.com/yaahc/eyre) which allows for this customization, but it hasn't been updated in over 4 months.

**Comment by uttarayan21** [comment]
Yeah I figured that. I have local changes removing anyhow and using thiserror crate and making a new error type containing all possible errors emitted by macchina.

Nov 19, 2021 10:15:57 PM Aziz Ben Ali ***@***.***>:

**Comment by uttarayan21** [comment]
So digging into the serde source code here https://docs.rs/serde/1.0.130/src/serde/de/mod.rs.html#282-284 it seems that the
 `` `hide_delimiters` for key `bar` at line 36 column 1`` part of the error is a `&'static str`. So how should I proceed ?

Making string operations on it doesn't really seem like  good idea.

**Comment by grtcdr** [comment]
> So digging into the serde source code here https://docs.rs/serde/1.0.130/src/serde/de/mod.rs.html#282-284 it seems that the `` `hide_delimiters` for key `bar` at line 36 column 1 `` part of the error is a `&'static str`. So how should I proceed ?

I'm not sure what's happening, can I get some more context around the problem?

**Comment by uttarayan21** [comment]
I meant that I can't modify any of the output of the mentioned line. But I can change other stuff.

Can you give a example of exactly what you want to show in the errors ?

**Comment by grtcdr** [comment]
> Can you give a example of exactly what you want to show in the errors ?
Nothing specific, really. Just a different kind of formatting (or colors).

**Comment by grtcdr** [comment]
I've tested your recent commit, and it seems like we're set!

Shall I merge?

**Comment by uttarayan21** [comment]
Yeah sure. IIRC it is done you can customize the output if you want, it is mostly inside main.

**Comment by grtcdr** [comment]
Before merging, we've got a report that config detection is [failing again](https://github.com/Macchina-CLI/macchina/issues/97#issuecomment-983124401) on macOS, just thought I'd let you know in case you have an idea why this might be occurring.

**Comment by uttarayan21** [comment]
I looked through the source I have no clue as to what might have caused this. I also don't have a MacOS vm in which I might test on currently.

**Comment by grtcdr** [comment]
> I also don't have a MacOS vm in which I might test on currently.

Neither do I, but I made some refactoring work to simplify (or make the bug apparent), not sure if that'll get it fixed.

**Review by grtcdr — APPROVED** [review]
Looks good!

**Pull request merged**
