### PR TITLE
Fix: dirs is not a iterator

### PR DESCRIPTION
**Pull request by sak96**
Fixes: #191

### CODE REVIEW

**Comment by grtcdr** [comment]
Any particular reason why I don't get this error?

**Comment by sak96** [comment]
More info #191

**Comment by sak96** [comment]
@grtcdr 

can be reproduced using:
```bash
docker run -it -v $(pwd):/mnt -w /mnt rust:1.52.1  cargo build
```

**Comment by sak96** [comment]
also did not know that you are from MARS :+1:

**Comment by grtcdr** [comment]
> Feel free to reject it if that is not suppose to be supported.

Well, most of us run the latest and greatest Rust compiler. Are you unable to upgrade?

> also did not know that you are from MARS

:alien:

**Comment by sak96** [comment]
I was able to update in one of the machines.
other one uses ubuntu repositories which has older version of rustc.
but there i could manually update the registry code.
in worst case i can install directly from my git repo.

**Comment by 123marvin123** [comment]
I think this should be fine for merging, what do you think @grtcdr ?

**Comment by grtcdr** [comment]
Although I don't plan on supporting older versions of rustc, I'll go ahead and merge it.

**Pull request merged**
