### PR TITLE
💬 Initial Text To Speech Support

### PR DESCRIPTION
**Pull request by grtcdr**
Macchina used to display, **but now it can speak!**

## How?

Through the magnificent work of @uttarayan21 who has provided bindings to [GoogleSpeech](https://github.com/desbma/GoogleSpeech) in his [google_speech crate](https://github.com/uttarayan21/google_speech_rs).

## Why?

It's unacceptable for us developers to push out solutions that only target one single demographic, those that _see_.

### CODE REVIEW

**Comment by grtcdr** [comment]
Hey @uttarayan21, unless you see there's any refactoring work to be done, I should probably merge this.

**Comment by uttarayan21** [comment]
I would take a look but both my laptop and desktop broke lol. So cant really check stuff.
If you think its ready you can merge it !!

**Comment by grtcdr** [comment]
> I would take a look but both my laptop and desktop broke lol. So cant really check stuff.

Woah, what happened? was it mean ol' Arch?

**Comment by uttarayan21** [comment]
Both were hardware failures. Fixing/re installing arch is pretty easy so that's not a problem.

**Comment by grtcdr** [comment]
> Both were hardware failures.

Damn, that's a bummer!

**Pull request merged**
