### PR TITLE
`v6`: breaking changes in themes, bug fixes and new features.

### LINKED ISSUE #199: [BUG] DE info for KDE Plasma
DE info for KDE Plasma doesn't display properly

Screenshot from 2021-11-06 05-10-55

Any way we could get a better looking message?
(I get that the `Distro` displays it)

### LINKED ISSUE #210: [FEATURE] Support system-wide installation
Allow themes to be loaded from `$XDG_DATA_HOME/macchina/themes` or `/usr/share/macchina/themes` so that macchina can be installed in the system. It will give priority to the folder `$XDG_DATA_CONFIG/macchina/themes` as it's the current settings and the folder that will contain custom user themes.

### PR DESCRIPTION
**Pull request by grtcdr**
# `v6` codename "Gallium" — CHANGELOG

We hope this is the last time we have to break your themes and configs, but hopefully you won't be so annoyed thanks to the new changes and features that this new version brings. _Go on, have a read_:

## Breaking Changes
- `hide_bar_delimiters` has been deprecated, **but the feature isn't gone**. You can hide your bar's delimiters using `hide_delimiters`, here's what'd look like:

```toml
[bar]
hide_delimiters = true
```

- `palette` has been deprecated, **and again, the feature is still here**. But, you now have to specify the type of variant you'd like to display and what glyph to use:
```toml
[palette]
type = "Full"
glyph = "●"
visible = true
```

## Bugfixes
- We've officially demoted `DESKTOP_SESSION`, preferring `XDG_CURRENT_DESKTOP` over it. `DESKTOP_SESSION` is essentially a fallback now. (closes #199)
- `--short-uptime` has been renamed to `--long-uptime`. Somehow, I forgot to rename the long version of this command-line flag, and you can verify this by comparing the flag name with the flag description — they contradict each other.

## New features
- _Every single_ option in a theme is now **optional**, feel free to remove anything you don't need!
- You can specify the **kind of border** you want macchina to use, under [box], you can add:
```
# Accepted values: "plain", "rounded" and "thick".
border = "plain"
```
- You can now tell macchina what pool of color to use when randomization is enabled, under [randomize], you can add:
```toml
# Accepted values: "base", "hexadecimal" and "indexed"
pool = "base"
```
- You can now use **indexed** colors, e.g. `38` and **hexadecimal** values, e.g. `#FFFFFF` for any option that accepts a _color_. (#193)
- You can now specify the glyph of the palette.
```toml
[palette]
glyph = "●"
```
- Added manpages — Woohoo!
  - There's one for the configuration file, and another for theming. 
- More datapaths to look at:
  - macchina now looks for themes in `/usr/share/macchina/themes`. (closes #210)
  - macOS: macchina now looks for themes in `~/.config/macchina/themes`.
- We've brought back the ability to toggle between showing your physical/logical core count.

## Miscellaneous
- When using `--list-themes`, themes are now listed below the directory that contains them, resulting in _much_ cleaner output.
- Some under-the-hood changes you might not notice, which mostly address the complexity of certain operations (hopefully improving performance).
- _Psst_... Gentoo users, macchina doesn't require **portage-utils** anymore.

### CODE REVIEW

**Comment by grtcdr** [comment]
@uttarayan21 somehow themes are properly sourced, but an error is raised.

`Error: IOError(Os { code: 2, kind: NotFound, message: "No such file or directory" })`

**Comment by uttarayan21** [comment]
Oh okay I'm looking into it.

**Comment by grtcdr** [comment]
this is happening in `create_theme`, seems like it's looking into `/usr/share/macchina/themes` and it's not finding the theme there (thus, throwing an error), but it does find it somewhere else (thus, sourcing the theme).

**Comment by grtcdr** [comment]
@uttarayan21 v6 is basically ready :)

I've got one bug left to squash, I'll definitely need your help on this one, I just can't seem to pinpoint why it's occurring. Basically what's happening is the separator's centering algorithm is doing it's calculations on hidden readouts, so it's always off by a few cells if you have certain (longer) readouts hidden. What do you think could be the culprit here?

**Comment by grtcdr** [comment]
@0323pin just thought I'd let you know I've finally managed to talk to X11 to get the resolution of every screen.

**Comment by 0323pin** [comment]
> @0323pin just thought I'd let you know I've finally managed to talk to X11 to get the resolution of every screen.

Thanks for the heads-up.
Wow, some breaking changes ahead 😄 
Also, I will need to fix the package to add the man page. I'll try to have it done today.

One thing though, will I need to link to x11 att compile time again?

**Comment by grtcdr** [comment]
> > @0323pin just thought I'd let you know I've finally managed to talk to X11 to get the resolution of every screen.

> Thanks for the heads-up. Wow, some breaking changes ahead smile Also, I will need to fix the package to add the man page. I'll try to have it done today.

Yeah, I've got a lot of documentation to update, hopefully this release goes smoothly.

> One thing though, will I need to link to x11 att compile time again?

Honestly, I don't know lol. I'm just happy I programmed my first (working) X11 client ever. Anyways, I'm working with [x11rb](https://github.com/psychon/x11rb), I'll try and figure that part out and let you know.

**Comment by 0323pin** [comment]
@grtcdr Couldn't resist 😄 

```
/home/pin/.config/macchina/themes()
2021-12-04 14:44 > ls
───┬────────────┬──────┬───────┬───────────────
 # │ name       │ type │ size  │ modified      
───┼────────────┼──────┼───────┼───────────────
 0 │ Oxide.toml │ File │ 1,081 │ 7 minutes ago 
───┴────────────┴──────┴───────┴───────────────

/home/pin/.config/macchina/themes()
2021-12-04 14:44 > macchina -v
macchina     6.0.0
libmacchina  3.9.0
/home/pin/.config/macchina/themes()
2021-12-04 14:45 > macchina
Error: Could not find "Oxide" in any of the default directories.
                                                                                        
 \\`-______,----__      Host        -  pin@mybox                                        
  \\        __,---`.    Machine     -  Hewlett-Packard HP EliteBook 820 G1 A3009DD10303
   \\       `.____      OS          -  NetBSD 9.99.92                                   
    \\-______,----`.    WM          -  LeftWM                                           
     \\                 Packages    -  193 (pkgsrc)                                     
      \\                Terminal    -  xterm                                            
       \\               Shell       -  nu                                               
        \\              Uptime      -  2h 28m                                           
         \\             CPU         -  Intel® Core™ i5-4210U CPU @ 1.70GHz (4)          
          \\            Resolution  -  1366x768                                         
           \\           Memory      -  1.2 GB/7.5 GB                                    
                        Battery     -  Full                                             

/home/pin/.config/macchina/themes()
2021-12-04 14:45 > macchina -d
Error: Could not find "Oxide" in any of the default directories.
Let's check your system for errors... Here's a summary:

We've collected 13 readouts, including 0 failed read(s) and 1 read(s) which resulted in a warning.
🎉 You are good to go! No failures detected.

1 of the 1 unsuccessful read(s) resulted in a warning:
Readout "DesktopEnvironment" threw a warning with message: You appear to be only running a window manager.
/home/pin/.config/macchina/themes()
2021-12-04 14:45 > 
```

Just one question, why is it not picking my theme? If you look at the output from `ls`, there is an `Oxide.toml` file in the _correct location_.

**Comment by grtcdr** [comment]
Sorry for editing your comment, I meant to reply to it.

**Comment by grtcdr** [comment]
> I've copied the theme to both /usr/share/macchina/themes and /usr/pkg/share/macchina/themes but, nothing changed.
> Why doesn't it read from ~/.config/macchina/themes?

It shouldn't be failing, I'm not sure what's causing this... 

So if I'm understanding you correctly, your themes aren't being sourced, but your configuration is?

**Comment by 0323pin** [comment]
@grtcdr yes, resoultion updates if I change it, you can relax :)

> It shouldn't be failing, I'm not sure what's causing this...

But, it does :(

Please try my `macchina.toml` and `Oxide.toml` to see if you can spot something.

```
# macchina.toml

interface     = "iwn0"
long_uptime   = false
current_shell = false
theme         = "Oxide"
show          = ["Host", "Machine", "OperatingSystem", "WindowManager", "Resolution", "Packages", "Terminal", "Shell", "Uptime", "Processor", "Memory", "Battery"]
# Other accepted values (case-sensitive): DesktopEnvironment, Backlight, LocalIP, ProcessorLoad
```

```
# Oxide.toml
# macchina theme

spacing         = 1
padding         = 0
hide_ascii      = true
separator       = " "
key_color       = "Yellow"
separator_color = "Yellow"

[palette]
type            = "Light"
glyph           = "●"
visible         = true

[bar]
hide_delimiters = true
glyph           = "●"
symbol_open     = '('
symbol_close    = ')'
visible         = false

[box]
title           = " "
visible         = false

[box.inner_margin]
x               = 2
y               = 1

[custom_ascii]
color           = "Yellow"

[randomize]
key_color       = false
separator_color = false

[keys]
host            = "Host"
kernel          = "Kernel"
battery         = "Battery"
os              = "OS"
de              = "DE"
wm              = "WM"
distro          = "Distro"
terminal        = "Terminal"
shell           = "Shell"
packages        = "Packages"
uptime          = "Uptime"
memory          = "Memory"
machine         = "Machine"
local_ip        = "IP"
backlight       = "Brightness"
resolution      = "Resolution"
cpu_load        = "CPU Load"
cpu             = "CPU"
```

**Comment by grtcdr** [comment]
Found it!

You're missing the `border` option under [box]:
```
border = "plain"
```

Jeez louise, the error message is horrendous, seems like `v6` is gonna have to wait a little while longer.

**Comment by grtcdr** [comment]
Just so you know, you can now tell macchina what pool of color to use when randomization is enabled, under [randomize], you can add:
```
pick_random_from = "Base" # Your average 16 color palette
```
It also takes `indexed` and `hexadecimal`, casing doesn't matter.

**Comment by grtcdr** [comment]
I'll try my absolute best to make all options _optional_, so that it doesn't end up annoying the shit out of somebody because they forget to add one or two lines. Because as of this very moment, macchina's split and transition has not been smooth.

**Comment by 0323pin** [comment]
@grtcdr awesome, thanks. I'll check-out these new features.

Yeah, there's been some breakage between releases but, I think you're getting where you want.

Making all _options_ optional actually makes sense. I prefer the output rather stripped down and could easily have a simpler theme file.

Will test as soon as I'm on my laptop again.

**Comment by grtcdr** [comment]
> I think you're getting where you want.

I appreciate it :)

It's going to take a while to get there, but hopefully by then macchina can become a very solid and viable option, for everyone.

> Making all options optional actually makes sense

I could maybe have this ready by the end of the day.

**Comment by grtcdr** [comment]
@0323pin as promised, everything is optional now :)

**Comment by grtcdr** [comment]
That's it boys, I'm disabling restyled. He's too annoying. It's making buttloads of PRs for single line changes.

**Comment by 0323pin** [comment]
> as promised, everything is optional now :)
phew, that was a lot of macros.

Great work :)

I guess, I need to rebuild from the latest commit sometime soon cause, I've added the things you pointed out but, I still get the same error :(

`Error: Could not find "Oxide" in any of the default directories.`

**Comment by grtcdr** [comment]
I'm sorry, maybe I forgot to mention a flag, but I'm sure that was what fixed it for me. Anyways, that won't be a problem anymore. I really enjoy how everything is optional now, thank you for reporting!

**Comment by 0323pin** [comment]
> I'm sorry, maybe I forgot to mention a flag

No worries, I'm the one playing with unreleased software 😆 

Which flag did you miss?
Just curious cause I've reverted to 5.0.5, at least until tomorrow 😄

**Comment by 0323pin** [comment]
Btw, are you using `leftwm` now? Again, just curious.

**Comment by grtcdr** [comment]
> Which flag did you miss? Just curious cause I've reverted to 5.0.5, at least until tomorrow smile

Not really sure, but as I said, you'll get less headaches now thanks to the just added error reporting for themes.

**Comment by 0323pin** [comment]
> Not really sure, but as I said, you'll get less headaches now thanks to the just added error reporting for themes.

This is actually great. Although, I don't mind _headaches_, they can be interesting sometimes.

Are you releasing 6 soon? If not, I'm building it tomorrow from the latest commit. No rush, just want to try.

**Comment by grtcdr** [comment]
> Are you releasing 6 soon? If not, I'm building it tomorrow from the latest commit. No rush, just want to try.

Definitely not, still got lots of testing to do, I want this release to be memorable and smooth :)

**Comment by 0323pin** [comment]
@grtcdr good, just wanted to know. Building it tomorrow 👍

**Comment by uttarayan21** [comment]
Looks like things are going smoothly. 

@grtcdr have you fixed the error showing up while still sourcing the theme ?
If not I'll make a pr.

Also it might be better to have an IRC or a matrix channel to talk in.

**Comment by 0323pin** [comment]
@grtcdr
> You should have a look at https://github.com/grtcdr/citron, libmacchina is expanding ... and it's going to be awesome.

Almost missed your edit but, now I saw it 😄 
I had a look at it and ... man, now I need to build it, don't I? 🤣 

Perhaps to early to have an opinion on it. But, hope these _notifications_ will be _on demand_ and not intrusive notifications that pop-up without asking.

@uttarayan21 
> it might be better to have an IRC or a matrix channel to talk in.

Good suggestion but, I use none. Actually, I don't use any chat client at all.

**Comment by grtcdr** [comment]
> @grtcdr have you fixed the error showing up while still sourcing the theme ?

Yeah, fixed.

**Comment by grtcdr** [comment]
> Almost missed your edit but, now I saw it smile I had a look at it and ... man, now I need to build it, don't I? rofl

Hahaha awesome! :heart: 

> Perhaps to early to have an opinion on it. But, hope these _notifications_ will be _on demand_ and not intrusive notifications that pop-up without asking.

Of course, they're on-demand (only and forever). I hate notifications too, but if I can use them to avoid having a panel constantly polling, I'll use them.

The [new changes in libmacchina](https://github.com/Macchina-CLI/libmacchina/commit/af1817b526651bf43dbffdb071df1acb315cef96), namely the new networking capabilities, planned for citron are going to eventually trickle their way down into macchina, they just need to be polished and thought-out carefully to make sense in a fetcher.

> Good suggestion but, I use none. Actually, I don't use any chat client at all.

I use matrix quite a bit, it's really easy to get into and enjoy even though it's quite a new protocol.

**Comment by uttarayan21** [comment]
> > Also it might be better to have an IRC or a matrix channel to talk in
> 
> That'd be nice, how do we set one up?
In matrix its really easy to setup just install any matrix client login and then click the + icon beside rooms dropdown. 
As for IRC I haven't really setup a IRC server but I guess it'll be quite a bit more involved than setting up matrix.

> Good suggestion but, I use none. Actually, I don't use any chat client at all.

You should try matrix its a decentralized opensource communications network. You can also self-host a server if you want.

**Comment by uttarayan21** [comment]
Also currently it gives two errors if the theme is not found so that needs to be fixed. Should be an easy fix I guess.

Also I can't seem to source files from `~/.local/share/macchina/themes` which is the user data directory for a user according to 
[XDG Base Directory Specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-0.6.html).
Screenshot from 2021-12-05 20-32-16

**Comment by 0323pin** [comment]
> Also I can't seem to source files from ~/.local/share/macchina/themes

@grtcdr is this where it's expecting to find the theme?
I thought it was `~/.config/macchina/themes`, at least there's where config files should be. Anyway, I don't really care for XDG conventions, where is the theme supposed to be?

**Comment by grtcdr** [comment]
> Also currently it gives two errors if the theme is not found so that needs to be fixed. Should be an easy fix I guess.

Yeah, I noticed that.

> Also I can't seem to source files from `~/.local/share/macchina/themes` which is the user data directory for a user according to...

We've switched from XDG_DATA_HOME a long time ago... What seems to be the issue?

**Comment by uttarayan21** [comment]
Oh I didn't realize It didn't source files from `XDG_DATA_HOME` anymore.
I was running a really old build till now I guess.

I still do however think that we should follow the XDG specification to store the theme files (maybe add the location of `~/.local/share/macchina/themes` as well as `~/.config/macchina/themes/`) to `extra::config_data_paths()`.

**Comment by grtcdr** [comment]
Sure, feel free to add it in :)

**Comment by grtcdr** [comment]
> In matrix its really easy to setup just install any matrix client login and then click the + icon beside rooms dropdown. As for IRC I haven't really setup a IRC server but I guess it'll be quite a bit more involved than setting up matrix.

I'll go ahead and do that, thank you for the suggestion :heart:

**Comment by uttarayan21** [comment]
I think they should be the same room.

**Comment by grtcdr** [comment]
> I think they should be the same room.

Done! https://matrix.to/#/#macchina:matrix.org

I'll try and find a cool badge so other people can access it too.

**Comment by grtcdr** [comment]
> Also currently it gives two errors if the theme is not found so that needs to be fixed. Should be an easy fix I guess.

@uttarayan21 Fixed with https://github.com/Macchina-CLI/macchina/pull/200/commits/a959c0a64c83b78a240a1a65709d94c679d2656f

**Comment by 0323pin** [comment]
@grtcdr Running v6.0.0 built from the latest commit now, all good. Thanks!

https://postimg.cc/K12MJ30F

**Comment by grtcdr** [comment]
Quite a clean theme you got there, would you mind adding it to contrib?

There's only so many elements in the periodic table, so we should probably start using a sensible naming scheme.

**Comment by 0323pin** [comment]
Sure, I'll make a PR later.

**Comment by 0323pin** [comment]
@grtcdr or, if you don't want to wait `curl` it from here, https://codeberg.org/pin/leftwm-netbsd/raw/branch/main/home/.config/macchina/themes/Oxide.toml

**Comment by grtcdr** [comment]
> @grtcdr or, if you don't want to wait `curl` it from here, https://codeberg.org/pin/leftwm-netbsd/raw/branch/main/home/.config/macchina/themes/Oxide.toml

No I don't mind waiting. If you merge a PR you get your name on the contributors list, which is always nice :)

**Comment by 0323pin** [comment]
> > @grtcdr or, if you don't want to wait `curl` it from here, https://codeberg.org/pin/leftwm-netbsd/raw/branch/main/home/.config/macchina/themes/Oxide.toml
> 
> No I don't mind waiting. If you merge a PR you get your name on the contributors list, which is always nice :)

Done :smile

**Comment by grtcdr** [comment]
@uttarayan21 The way we handle `MACCHINA_CONF` does not comply with the way macchina searches for themes, I think it's better to rewrite it from scratch.

**Comment by uttarayan21** [comment]
Isn't MACCHINA_CONF only for the config file ?

**Comment by grtcdr** [comment]
> Isn't MACCHINA_CONF only for the config file ?

Yeah, but that's not enough to source the themes. If macchina can't find its config in predefined locations, it also won't find its themes.

**Comment by grtcdr** [comment]
I've fixed the spacing bug, v6 will release soon :heart:

**Pull request merged**
